vita_boy:
  kp: [
        200.0, 150.0, 100.0, 150.0, 30.0, 30.0, 
        200.0, 150.0, 100.0, 150.0, 30.0, 30.0, 
        200.0, 30.0, 30.0, 
        15.0, 15.0, 15.0, 15.0, 15.0, 10.0, 10.0, 
        15.0, 15.0, 15.0, 15.0, 15.0, 10.0, 10.0
      ]

  kd: [
        5.0, 4.0, 3.0, 4.0, 2.0, 2.0, 
        5.0, 4.0, 3.0, 4.0, 2.0, 2.0, 
        5.0, 2.0, 2.0, 
        1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 
        1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0
      ]

  default_dof_pos: [
                    -0.312, 0.0, 0.0, 0.669, -0.363, 0.0,
                    -0.312, 0.0, 0.0, 0.669, -0.363, 0.0,
                    0.0, 0.0, 0.0,
                    0.2,  0.2, 0.0, 0.6, 0.0, 0.0, 0.0,
                    0.2, -0.2, 0.0, 0.6, 0.0, 0.0, 0.0
                  ]

  num_observations: 96
  num_actions: 29
  policy_name: "vita_boy_loco.onnx"
  control_decimation: 10
  observations_history: 10
  dof_pos_scale: 1
  dof_vel_scale: 1
  lin_vel_scale: 1
  ang_vel_scale: 1
  clip_obs: 100
  clip_action: 100
  clip_actions_lower: [-100.0, -100.0, -100.0, -100.0, -100.0, -100.0,
                       -100.0, -100.0, -100.0, -100.0, -100.0, -100.0,
                       -100.0, -100.0, -100.0,
                       -100.0, -100.0, -100.0, -100.0, -100.0, -100.0, -100.0,
                       -100.0, -100.0, -100.0, -100.0, -100.0, -100.0, -100.0]
  clip_actions_upper: [100.0, 100.0, 100.0, 100.0, 100.0, 100.0,
                       100.0, 100.0, 100.0, 100.0, 100.0, 100.0,
                       100.0, 100.0, 100.0,
                       100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0,
                       100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0]
  action_scale: [
                  0.25, 0.25, 0.25, 0.25, 0.25, 0.25,
                  0.25, 0.25, 0.25, 0.25, 0.25, 0.25,
                  0.25, 0.25, 0.25,
                  0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25,
                  0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25
                ]
  commands_scale: [1.0, 1.0, 1.0]
  joint_mapping: [0, 6,  12, 
                  1, 7,  13, 
                  2, 8,  14, 
                  3, 9,  15, 22, 
                  4, 10, 16, 23, 
                  5, 11, 17, 24, 
                         18, 25, 
                         19, 26, 
                         20, 27, 
                         21, 28]
  observations: ["ang_vel", "gravity_vec", "commands", "dof_pos", "dof_vel", "actions"]

  intra_op_num_threads: 1
  inter_op_num_threads: 1
  bind_main_thread_to_core: false
  bind_inference_thread_to_core: true
  assigned_inference_cores: [7]
  transition_time: 0.5